name: YouTube Analytics Refresh

on:
  # Runs at midnight Pacific. GitHub cron is UTC, so:
  # - 07:05 UTC ≈ 12:05 AM PT during DST (Mar–Nov)
  # - 08:05 UTC ≈ 12:05 AM PT during Standard Time (Nov–Mar)
  schedule:
    - cron: '5 7 * * *'   # 12:05 AM PT when DST is ON
    - cron: '5 8 * * *'   # 12:05 AM PT when DST is OFF
  workflow_dispatch: {}    # allow manual runs

permissions:
  contents: write          # needed to push changes

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Recreate OAuth files from secrets
        env:
          YT_CLIENT_SECRET_JSON: ${{ secrets.YT_CLIENT_SECRET_JSON }}
          YT_TOKEN_JSON: ${{ secrets.YT_TOKEN_JSON }}
        run: |
          # adjust cd if your script lives in a subfolder
          cd kepilot-youtube_channel
          printf '%s' "$YT_CLIENT_SECRET_JSON" > client_secret.json
          printf '%s' "$YT_TOKEN_JSON" > token.json

      - name: Install deps
        run: |
            python -m pip install --upgrade pip
            pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 pandas

      - name: Run reports (last 30 days)
        run: |
          cd kepilot-youtube_channel
          python yta_master_reports.py

      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yta_outputs/*.csv || true
          git commit -m "Automated YTA refresh: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
