name: YouTube Analytics Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * *"   # 08:05 UTC (~12:05 AM PT during Standard Time)

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history so we can pull/rebase)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Ensure repo root is on PYTHONPATH
        run: echo "PYTHONPATH=.:$PYTHONPATH" >> $GITHUB_ENV

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 pandas

      - name: Write token.json from secret
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: |
          printf '%s' "$TOKEN_JSON" > token.json
          python -c "import json; json.load(open('token.json')); print('token.json JSON OK')"

      - name: Run reports (30 full days in PT with 2-day lag)
        env:
          TZ: America/Los_Angeles
        run: |
          END="$(date -d '2 days ago' +%F)"
          START="$(date -d '32 days ago' +%F)"
          echo "Range: $START -> $END (America/Los_Angeles)"
          python yta_run_reports.py --start "$START" --end "$END"

      - name: Commit and push outputs (pull-rebase first)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yta_outputs/*.csv 2>/dev/null || true
          git add *.csv 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "Automated YTA refresh: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          else
            echo "No changes to commit."
          fi
          git config pull.rebase true
          git pull origin main || true
          git push origin main || { echo "Push failed once; retrying after rebase..."; git pull --rebase origin main || true; git push origin main; }




