name: YouTube Analytics Refresh

on:
  workflow_dispatch: {}
  schedule:
    - cron: '59 6 * * *'   # 11:59 PM PT during Daylight Saving (UTC-7)
    - cron: '59 7 * * *'   # 11:59 PM PT during Standard Time (UTC-8)

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore OAuth files from secrets (to repo root)
        env:
          YT_CLIENT_SECRET_JSON: ${{ secrets.YT_CLIENT_SECRET_JSON }}
          YT_TOKEN_JSON: ${{ secrets.YT_TOKEN_JSON }}
        run: |
          printf '%s' "$YT_CLIENT_SECRET_JSON" > client_secret.json
          printf '%s' "$YT_TOKEN_JSON" > token.json

      - name: Ensure repo root is on PYTHONPATH
        run: echo "PYTHONPATH=.:$PYTHONPATH" >> $GITHUB_ENV

      - name: Debug paths
        run: |
          pwd
          ls -la

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 pandas

      - name: Run reports
        run: python yta_run_reports.py

      - name: Commit and push outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yta_outputs/*.csv || true
          git commit -m "Automated YTA refresh: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
